name: Build

on:
  push:
    branches: [main]

permissions:
  packages: write
  contents: write

env:
  CROSS_COMPILE: "./toolchain/arm-cortex_a7-linux-gnueabihf-linaro_4.9/bin/arm-cortex_a7-linux-gnueabihf-"
  KCFLAGS: "-pipe -mtune=cortex-a7 -march=armv7-a -mfpu=neon-vfpv4"
  MTK_ROOT_CUSTOM: "./mediatek"
  TARGET_PRODUCT: "lenovo89_tb_x10_jb2"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Env cache (restore)
        id: cache
        uses: actions/cache/restore@v4
        with:
          path: ./
          key: env-cache-${{ github.sha }}
          restore-keys: env-cache-

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup env
        run: |
          sudo apt-get -y install python2
          sudo ln -sf /usr/bin/bash /usr/bin/sh
          sudo ln -sf /usr/bin/python2 /usr/bin/python

      - name: Mediatek Config
        run: |
          source ./mediatek/build/shell.sh ./ kernel
          make mediatek-configs

      - name: Config
        run: make oldconfig

      - name: Build
        run: make -j6

      - name: Release
        run: gh release create "build-$(date +%Y%m%d%H%M%S)" -t "build-$(date +%Y%m%d%H%M%S)" --generate-notes
        working-directory: build_result

      - name: Env cache (save)
        if: ${{ !cancelled() }}
        uses: actions/cache/save@v4
        with:
          path: ./
          key: env-cache-${{ github.sha }}
